# src/config/mapeamentos.py

# Mapeamento de Filial para Região (versão final e completa)
# Sincronizado com a lista de filiais únicas da query SQL.
mapa_regiao = {
    # --- FILIAIS GRITSCH (NOME COMPLETO) ---
    'Gritsch Blumenau': 'SUL',
    'Gritsch Brasília': 'CENTRO OESTE',
    'Gritsch Campo Grande': 'CENTRO OESTE',
    'Gritsch Cascavel': 'SUL',
    'Gritsch Chapecó': 'SUL',
    'Gritsch Criciuma': 'SUL',
    'Gritsch Cuiabá': 'CENTRO OESTE',
    'Gritsch Curitiba Base': 'SUL',
    'Gritsch Curitiba ECT': 'SUL',
    'Gritsch Curitibanos': 'SUL',
    'Gritsch Florianópolis': 'SUL',
    'Gritsch Goiânia': 'CENTRO OESTE',
    'Gritsch Guarapuava': 'SUL',
    'Gritsch Itumbiara': 'CENTRO OESTE',
    'Gritsch Joinville': 'SUL',
    'Gritsch Laranjeiras do Sul': 'SUL',
    'Gritsch Londrina': 'SUL',
    'Gritsch Maringá': 'SUL',
    'Gritsch Palmas': 'NORTE',
    'Gritsch Pato Branco': 'SUL',
    'Gritsch Ponta Grossa': 'SUL',
    'Gritsch Porto Alegre': 'SUL',
    'Gritsch Rio Verde': 'CENTRO OESTE',
    'Gritsch Rondonópolis': 'CENTRO OESTE',
    'Gritsch Salvador': 'NORDESTE',
    'Gritsch Sinop': 'CENTRO OESTE',
    'Gritsch São Paulo (Freguesia)': 'SUDESTE',
    'Gritsch São Paulo (Perus)': 'SUDESTE',

    # --- FILIAIS GRITSCH (SIGLAS) ---
    'GRITSCH - BLN': 'SUL',
    'GRITSCH - BSB': 'CENTRO OESTE',
    'GRITSCH - CBL': 'CENTRO OESTE',
    'GRITSCH - CGB': 'CENTRO OESTE',
    'GRITSCH - CGR': 'CENTRO OESTE',
    'GRITSCH - CHA': 'SUL',
    'GRITSCH - CRI': 'SUL',
    'GRITSCH - CSC': 'SUL',
    'GRITSCH - CTB': 'SUL',
    'GRITSCH - CWB (BASE)': 'SUL',
    'GRITSCH - CWB (DIR)': 'SUL',
    'GRITSCH - CWB (ECT)': 'SUL',
    'GRITSCH - FLN': 'SUL',
    'GRITSCH - GOI': 'CENTRO OESTE',
    'GRITSCH - GPA': 'SUL',
    'GRITSCH - ITR': 'CENTRO OESTE',
    'GRITSCH - JOI': 'SUL',
    'GRITSCH - LDB': 'SUL',
    'GRITSCH - MATRIZ': 'SUDESTE',
    'GRITSCH - MGA': 'SUL',
    'GRITSCH - PBC': 'SUL',
    'GRITSCH - PGR': 'SUL',
    'GRITSCH - PMW': 'NORTE',
    'GRITSCH - POA': 'SUL',
    'GRITSCH - RDN': 'CENTRO OESTE',
    'GRITSCH - RVD': 'CENTRO OESTE',
    'GRITSCH - SAO (FREGUESIA)': 'SUDESTE',
    'GRITSCH - SAO (PERUS)': 'SUDESTE',
    'GRITSCH - SNO': 'CENTRO OESTE',
    'GRITSCH - SSA': 'NORDESTE',

    # --- FILIAIS REFERÊNCIA ---
    'REFERÊNCIA ARAGUAÍNA': 'NORTE',
    'REFERÊNCIA BALSAS': 'NORDESTE',
    'REFERÊNCIA BRASILIA': 'CENTRO OESTE',
    'REFERÊNCIA CUIABÁ LOJA': 'CENTRO OESTE',
    'REFERÊNCIA CURITIBA': 'SUL',
    'REFERÊNCIA FOZ DO IGUAÇU': 'SUL',
    'REFERÊNCIA GOIÂNIA AV RIO VERDE': 'CENTRO OESTE',
    'REFERÊNCIA GOIÂNIA LOJA': 'CENTRO OESTE',
    'REFERÊNCIA LUIS EDUARDO MAGALHÃES': 'NORDESTE',
    'REFERÊNCIA MARINGÁ': 'SUL',
    'REFERÊNCIA RIBEIRAO PRETO': 'SUDESTE',
    'REFERÊNCIA SALVADOR': 'NORDESTE',
    'REFERÊNCIA SINOP': 'CENTRO OESTE',
    'REFERÊNCIA SÃO PAULO': 'SUDESTE',
    'REFERÊNCIA VILHENA': 'NORTE',

    # --- RATEIOS ---
    'RATEIO - GRI': 'RATEIO',
    'RATEIO - REF': 'RATEIO',
    'RATEIO - GRI/REF': 'RATEIO'
}


